"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import glob
from setuptools import setup

APP = ['basic_example.py']
DATA_FILES = [('docs', glob.glob('docs/*.*')), ('NodeGraphQt', glob.glob('NodeGraphQt/*.*')), ('examples', glob.glob('examples/*.*')),]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
